services:
  read_service:
    build: ./read_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./read_service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://postgres:rms46os211@localhost/postgres
    depends_on:
      - person_db

  update_service:
    build: ./update_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./update_service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://postgres:rms46os211@localhost/postgres
    depends_on:
      - person_db

  person_db:
    image: postgres:14
    volumes:
      - postgres_data_person:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rms46os211
      - POSTGRES_DB=postgres
    
  nginx:
  image: nginx:latest
  ports:
    - "8000:8000"
  volumes: 
    - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
  depends_on:
    - read_service
    - update_service

volumes:
  postgres_data_person:
